version: '3.9'

services:
  app:
    build: .
    image: open-inventory-backend
    container_name: open-inventory-backend
    ports:
      - "8003:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0
      - POSTGRES_DB=open-inventory-backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    depends_on:
      - db
  db:
    container_name: open-inventory-db
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0
      - POSTGRES_DB=open-inventory-backend
    ports:
      - "5434:5432"
volumes:
  data:
